#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_BTCP_VERSION=${VERSION_STRING[2]}
ELECTRUM_BTCP_VERSION=${ELECTRUM_BTCP_VERSION#\'}
ELECTRUM_BTCP_VERSION=${ELECTRUM_BTCP_VERSION%\'}
DOTS=`echo $ELECTRUM_BTCP_VERSION |  grep -o "\." | wc -l`
if [[ $DOTS -lt 3 ]]; then
    ELECTRUM_BTCP_APK_VERSION=$ELECTRUM_BTCP_VERSION.0
else
    ELECTRUM_BTCP_APK_VERSION=$ELECTRUM_BTCP_VERSION
fi
export ELECTRUM_BTCP_VERSION
export ELECTRUM_BTCP_APK_VERSION
